Repository mdflynn/game-sleuth, pull requests merged in 2021-01, with the labels that each got.

#8 Feature/initial buildout
  .eslintcache
  package-lock.json
  package.json
  src/APIcalls.tsx
  src/App.tsx
  src/App/App.scss
  src/App/App.test.tsx
  src/App/App.tsx
  src/MainPage/MainPage.scss
  src/MainPage/MainPage.tsx
  src/SearchDisplay/SearchDisplay.scss
  src/SearchDisplay/SearchDisplay.tsx
  src/SearchForm/SearchForm.scss
  src/SearchForm/SearchForm.tsx
  src/index.tsx
  src/interfaces/MyBoardGame.interface.tsx
Labels: bones

#14 Feature/search form
  .eslintcache
  .gitignore
  package-lock.json
  package.json
  src/SearchForm/SearchForm.scss
  src/SearchForm/SearchForm.tsx
Labels: enhancement

#15 Feature/search display buildout
  .eslintcache
  src/GamePreview/GamePreview.scss
  src/GamePreview/GamePreview.tsx
  src/SearchDisplay/SearchDisplay.tsx
  src/interfaces/MyBoardGame.interface.tsx
Labels: enhancement

#18 Feature/search api
  .eslintcache
  src/APIcalls.tsx
  src/App/App.tsx
  src/MainPage/MainPage.tsx
  src/SearchDisplay/SearchDisplay.tsx
  src/SearchForm/SearchForm.tsx
Labels: enhancement

#25 Reformat SoloGameView, pass in GameData for state
  .eslintcache
  src/App/App.tsx
  src/SearchDisplay/SearchDisplay.tsx
  src/SoloGameView/SoloGameView.scss
  src/SoloGameView/SoloGameView.tsx
  src/interfaces/MyBoardGame.interface.tsx
Labels: enhancement

#27 Feature/quick fix
  .eslintcache
  src/APIcalls.tsx
  src/App/App.tsx
  src/MainPage/MainPage.tsx
  src/SearchDisplay/SearchDisplay.tsx
  src/SearchForm/SearchForm.tsx
  src/SoloGameView/SoloGameView.tsx
Labels: enhancement

#29 Add 5 passing App tests
  package-lock.json
  package.json
  src/App/App.test.tsx
Labels: testing

#32 Add integration testing to App.test
  .eslintcache
  package-lock.json
  package.json
  src/App/App.test.tsx
  src/App/App.tsx
Labels: testing

#33 Feature/solo view buildout
  .eslintcache
  src/APIcalls.tsx
  src/SoloGameView/SoloGameView.scss
  src/SoloGameView/SoloGameView.tsx
  src/_variables.scss
  src/assets/mag-hand-right.png
  src/assets/mag-hand.png
  src/interfaces/MyBoardGame.interface.tsx
Labels: enhancement

#37 Testing/searchdisplay
  .eslintcache
  src/App/App.test.tsx
  src/SearchDisplay/SearchDisplay.test.tsx
Labels: testing

#38 Feature/search form testing
  package-lock.json
  package.json
  src/SearchForm/SearchForm.scss
  src/SearchForm/SearchForm.test.tsx
  src/SearchForm/SearchForm.tsx
Labels: enhancement

#40 Feature/search by name
  .eslintcache
  src/App/App.test.tsx
  src/SearchForm/SearchForm.scss
  src/SearchForm/SearchForm.test.tsx
  src/SearchForm/SearchForm.tsx
Labels: enhancement

#42 Feature/nav
  .eslintcache
  src/App/App.test.tsx
  src/App/App.tsx
  src/Nav/Nav.scss
  src/Nav/Nav.test.tsx
  src/Nav/Nav.tsx
  src/assets/sleuth.png
Labels: enhancement

#44 Feature/solo view redesign
  .eslintcache
  src/App/App.scss
  src/SearchForm/SearchForm.scss
  src/SoloGameView/SoloGameView.scss
  src/SoloGameView/SoloGameView.test.tsx
  src/SoloGameView/SoloGameView.tsx
  src/assets/game-background.jpg
Labels: enhancement

#45 Feature/searchdisplay design
  .eslintcache
  src/GamePreview/GamePreview.scss
  src/GamePreview/GamePreview.tsx
  src/MainPage/MainPage.scss
  src/MainPage/MainPage.tsx
  src/SearchDisplay/SearchDisplay.scss
  src/SearchDisplay/SearchDisplay.tsx
Labels: enhancement

#47 Testing/gamepreview
  .eslintcache
  src/GamePreview/GamePreview.test.tsx
Labels: testing

#49 Add catch for no search results
  .eslintcache
  src/SearchDisplay/SearchDisplay.tsx
Labels: enhancement

#52 Bug/search results
  .eslintcache
  src/SearchForm/SearchForm.tsx
Labels: bug

#53 Fix/css tweaks
  .eslintcache
  src/App/App.scss
  src/GamePreview/GamePreview.scss
  src/GamePreview/GamePreview.tsx
  src/MainPage/MainPage.scss
  src/MainPage/MainPage.tsx
  src/Nav/Nav.scss
  src/Nav/Nav.tsx
  src/SearchDisplay/SearchDisplay.scss
  src/SearchDisplay/SearchDisplay.tsx
  src/SearchForm/SearchForm.scss
  src/SearchForm/SearchForm.tsx
  src/SoloGameView/SoloGameView.tsx
  src/assets/mag-hand-right.png
Labels: enhancement

#54 Fix/fetch styling fixes
  .eslintcache
  src/GamePreview/GamePreview.scss
  src/GamePreview/GamePreview.tsx
  src/MainPage/MainPage.scss
  src/SearchDisplay/SearchDisplay.scss
  src/SearchDisplay/SearchDisplay.tsx
  src/SearchForm/SearchForm.scss
  src/SoloGameView/SoloGameView.scss
  src/SoloGameView/SoloGameView.tsx
Labels: enhancement

#56 Feature/readme
  README.md
Labels: documentation, enhancement

#57 Deploy to GH Pages
  .eslintcache
  package-lock.json
  package.json
Labels: enhancement

#59 Correct deployment route
  .eslintcache
  src/App/App.tsx
Labels: bug
